on  :
  workflow_call:
    inputs:
      name:
        type    : string
        required: true
      value:
        type    : string
        required: true
      token:
        type    : string
        required: true
env:
  GH_TOKEN: ${{ inputs.token }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check the variable
        run : |
          gh api --method GET \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables/${{ inputs.name }}
          if [ $? -eq 0 ]; then
            echo "isset=true" >> $GITHUB_ENV
          fi
        continue-on-error: true
      - name: Create the variable
        if  : ${{ !env.isset }}
        run : |
          gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables \
            -f name='${{ inputs.name }}' \
            -f value="${{ inputs.value }}"
      - name: Update the variable
        if  : ${{ env.isset }}
        run : |
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/variables/${{ inputs.name }} \
            -f name='${{ inputs.name }}' \
            -f value="${{ inputs.value }}"